export const standardObjectConfigs = [
  { type: "COMPANY", attributeName: "Name" },
  { type: "DEAL", attributeName: "Deal name" },
  { type: "PERSON", attributeName: "Name" },
  { type: "USER", attributeName: "Primary email address" },
  { type: "WORKSPACE", attributeName: "Name" },
];

export const standardObjects = (workspaceId) => [
  {
    singular: "Company",
    plural: "Companies",
    slug: "companies",
    type: "COMPANY",
    isStandard: true,
    attributes: {
      create: [
        {
          name: "Domains",
          attributeType: "DOMAIN",
          isUnique: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Name",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Description",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Team",
          attributeType: "RELATIONSHIP",
          relationshipType: "ONE_TO_MANY",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "List entries",
          attributeType: "RECORD",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Categories",
          attributeType: "MULTI_SELECT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Primary location",
          attributeType: "LOCATION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Logo URL",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Facebook",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Instagram",
          attributeType: "TEXT",
          isSystem: true,
          workspaceId,
        },
        {
          name: "LinkedIn",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Twitter",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Twitter follower count",
          attributeType: "NUMBER",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Estimated ARR",
          attributeType: "SELECT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Funding raised",
          attributeType: "CURRENCY",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Foundation date",
          attributeType: "DATE",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Employee range",
          attributeType: "SELECT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "First calendar interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Last calendar interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Next calendar interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "First email interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Last email interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "First interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Last interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Next interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Connection strength",
          attributeType: "SELECT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Strongest connection",
          attributeType: "USER",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Next due task",
          attributeType: "RECORD",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Associated deals",
          attributeType: "RELATIONSHIP",
          relationshipType: "ONE_TO_MANY",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Associated workspaces",
          attributeType: "RELATIONSHIP",
          relationshipType: "ONE_TO_MANY",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created at",
          attributeType: "TIMESTAMP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created by",
          attributeType: "USER",
          isSystem: true,
          workspaceId,
        },
      ],
    },
  },
  {
    singular: "Deal",
    plural: "Deals",
    slug: "deals",
    type: "DEAL",
    isStandard: true,
    attributes: {
      create: [
        {
          name: "Deal name",
          attributeType: "TEXT",
          isRequired: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Deal stage",
          attributeType: "STATUS",
          isRequired: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "List entries",
          attributeType: "RECORD",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Deal owner",
          attributeType: "USER",
          isRequired: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Deal value",
          attributeType: "CURRENCY",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Associated people",
          attributeType: "RELATIONSHIP",
          relationshipType: "MANY_TO_MANY",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Associated company",
          attributeType: "RELATIONSHIP",
          relationshipType: "MANY_TO_ONE",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created at",
          attributeType: "TIMESTAMP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created by",
          attributeType: "USER",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Next due task",
          attributeType: "RECORD",
          isSystem: true,
          workspaceId,
        },
      ],
    },
  },
  {
    singular: "Person",
    plural: "People",
    slug: "people",
    type: "PERSON",
    isStandard: true,
    attributes: {
      create: [
        {
          name: "Name",
          attributeType: "PERSONAL_NAME",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Email addresses",
          attributeType: "EMAIL_ADDRESS",
          isUnique: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Description",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Company",
          attributeType: "RELATIONSHIP",
          relationshipType: "MANY_TO_ONE",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Job title",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Avatar URL",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Phone numbers",
          attributeType: "PHONE_NUMBER",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Primary location",
          attributeType: "LOCATION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "List entries",
          attributeType: "RECORD",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Facebook",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Instagram",
          attributeType: "TEXT",
          isSystem: true,
          workspaceId,
        },
        {
          name: "LinkedIn",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Twitter",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Twitter follower count",
          attributeType: "NUMBER",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "First calendar interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Last calendar interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Next calendar interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "First email interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Last email interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "First interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Last interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Next interaction",
          attributeType: "INTERACTION",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Connection strength",
          attributeType: "SELECT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Strongest connection",
          attributeType: "USER",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Next due task",
          attributeType: "RECORD",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Associated deals",
          attributeType: "RELATIONSHIP",
          relationshipType: "MANY_TO_MANY",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Associated users",
          attributeType: "RELATIONSHIP",
          relationshipType: "ONE_TO_MANY",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created at",
          attributeType: "TIMESTAMP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created by",
          attributeType: "USER",
          isSystem: true,
          workspaceId,
        },
      ],
    },
  },
  {
    singular: "User",
    plural: "Users",
    slug: "users",
    type: "USER",
    isStandard: true,
    attributes: {
      create: [
        {
          name: "Person",
          attributeType: "RELATIONSHIP",
          relationshipType: "MANY_TO_ONE",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Primary email address",
          attributeType: "EMAIL_ADDRESS",
          isUnique: true,
          isRequired: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created at",
          attributeType: "TIMESTAMP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created by",
          attributeType: "USER",
          isSystem: true,
          workspaceId,
        },
        {
          name: "List entries",
          attributeType: "RECORD",
          isSystem: true,
          workspaceId,
        },
        {
          name: "User ID",
          attributeType: "TEXT",
          isUnique: true,
          isRequired: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Workspaces",
          attributeType: "RELATIONSHIP",
          relationshipType: "MANY_TO_MANY",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Next due task",
          attributeType: "RECORD",
          isSystem: true,
          workspaceId,
        },
      ],
    },
  },
  {
    singular: "Workspace",
    plural: "Workspaces",
    slug: "workspaces",
    type: "WORKSPACE",
    isStandard: true,
    attributes: {
      create: [
        {
          name: "Workspace ID",
          attributeType: "TEXT",
          isUnique: true,
          isRequired: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Name",
          attributeType: "TEXT",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Users",
          attributeType: "RELATIONSHIP",
          relationshipType: "MANY_TO_MANY",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Company",
          attributeType: "RELATIONSHIP",
          relationshipType: "MANY_TO_ONE",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Avatar URL",
          attributeType: "TEXT",
          isSystem: true,
          workspaceId,
        },
        {
          name: "List entries",
          attributeType: "RECORD",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created at",
          attributeType: "TIMESTAMP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created by",
          attributeType: "USER",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Next due task",
          attributeType: "RECORD",
          isSystem: true,
          workspaceId,
        },
      ],
    },
  },
];
