export const standardObjectConfigs = [
  { type: "COMPANY", attributeName: "Name" },
  { type: "DEAL", attributeName: "Deal name" },
  { type: "PERSON", attributeName: "Name" },
  { type: "USER", attributeName: "Primary email address" },
  { type: "WORKSPACE", attributeName: "Name" },
];

export const standardRelationships = [
  {
    sourceObjectType: "COMPANY",
    sourceAttributeName: "Team",
    targetObjectType: "PERSON",
    targetAttributeName: "Company",
    relationshipType: "ONE_TO_MANY",
  },
  {
    sourceObjectType: "COMPANY",
    sourceAttributeName: "Associated deals",
    targetObjectType: "DEAL",
    targetAttributeName: "Associated company",
    relationshipType: "ONE_TO_MANY",
  },
  {
    sourceObjectType: "COMPANY",
    sourceAttributeName: "Associated workspaces",
    targetObjectType: "WORKSPACE",
    targetAttributeName: "Company",
    relationshipType: "ONE_TO_MANY",
  },
  {
    sourceObjectType: "DEAL",
    sourceAttributeName: "Associated people",
    targetObjectType: "PERSON",
    targetAttributeName: "Associated deals",
    relationshipType: "MANY_TO_MANY",
  },
  {
    sourceObjectType: "DEAL",
    sourceAttributeName: "Associated company",
    targetObjectType: "COMPANY",
    targetAttributeName: "Associated deals",
    relationshipType: "MANY_TO_ONE",
  },
  {
    sourceObjectType: "PERSON",
    sourceAttributeName: "Company",
    targetObjectType: "COMPANY",
    targetAttributeName: "Team",
    relationshipType: "MANY_TO_ONE",
  },
  {
    sourceObjectType: "PERSON",
    sourceAttributeName: "Associated deals",
    targetObjectType: "DEAL",
    targetAttributeName: "Associated people",
    relationshipType: "MANY_TO_MANY",
  },
  {
    sourceObjectType: "PERSON",
    sourceAttributeName: "Associated users",
    targetObjectType: "USER",
    targetAttributeName: "Person",
    relationshipType: "ONE_TO_MANY",
  },
  {
    sourceObjectType: "USER",
    sourceAttributeName: "Person",
    targetObjectType: "PERSON",
    targetAttributeName: "Associated users",
    relationshipType: "MANY_TO_ONE",
  },
  {
    sourceObjectType: "USER",
    sourceAttributeName: "Workspaces",
    targetObjectType: "WORKSPACE",
    targetAttributeName: "Users",
    relationshipType: "MANY_TO_MANY",
  },
  {
    sourceObjectType: "WORKSPACE",
    sourceAttributeName: "Users",
    targetObjectType: "USER",
    targetAttributeName: "Workspaces",
    relationshipType: "MANY_TO_MANY",
  },
  {
    sourceObjectType: "WORKSPACE",
    sourceAttributeName: "Company",
    targetObjectType: "COMPANY",
    targetAttributeName: "Associated workspaces",
    relationshipType: "MANY_TO_ONE",
  },
];

export const standardObjects = (workspaceId) => [
  {
    singular: "Company",
    plural: "Companies",
    slug: "companies",
    type: "COMPANY",
    isStandard: true,
    attributes: {
      create: [
        {
          name: "Domains",
          attributeType: "DOMAIN",
          isUnique: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Name",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Description",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Team",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Logo URL",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Associated deals",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Associated workspaces",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created at",
          attributeType: "TIMESTAMP",
          isSystem: true,
          isReadOnly: true,
          workspaceId,
        },
      ],
    },
  },
  {
    singular: "Deal",
    plural: "Deals",
    slug: "deals",
    type: "DEAL",
    isStandard: true,
    attributes: {
      create: [
        {
          name: "Deal name",
          attributeType: "TEXT",
          isRequired: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Deal stage",
          attributeType: "STATUS",
          isRequired: true,
          isSystem: true,
          config: {
            options: [
              "Open",
              "Opportunity",
              "Negotiating",
              "Proposal Sent",
              "Closed",
            ],
          },
          workspaceId,
        },
        {
          name: "Associated people",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Associated company",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created at",
          attributeType: "TIMESTAMP",
          isSystem: true,
          workspaceId,
        },
      ],
    },
  },
  {
    singular: "Person",
    plural: "People",
    slug: "people",
    type: "PERSON",
    isStandard: true,
    attributes: {
      create: [
        {
          name: "Name",
          attributeType: "PERSONAL_NAME",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Primary email",
          attributeType: "EMAIL_ADDRESS",
          isUnique: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Description",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Company",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Job title",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Avatar URL",
          attributeType: "TEXT",
          isSystem: true,
          isEnriched: true,
          workspaceId,
        },
        {
          name: "Associated deals",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Associated users",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created at",
          attributeType: "TIMESTAMP",
          isSystem: true,
          isReadOnly: true,
          workspaceId,
        },
      ],
    },
  },
  {
    singular: "User",
    plural: "Users",
    slug: "users",
    type: "USER",
    isStandard: true,
    attributes: {
      create: [
        {
          name: "Person",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Primary email address",
          attributeType: "EMAIL_ADDRESS",
          isUnique: true,
          isRequired: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created at",
          attributeType: "TIMESTAMP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "User ID",
          attributeType: "TEXT",
          isUnique: true,
          isRequired: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Workspaces",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          workspaceId,
        },
      ],
    },
  },
  {
    singular: "Workspace",
    plural: "Workspaces",
    slug: "workspaces",
    type: "WORKSPACE",
    isStandard: true,
    attributes: {
      create: [
        {
          name: "Workspace ID",
          attributeType: "TEXT",
          isUnique: true,
          isRequired: true,
          isSystem: true,
          workspaceId,
        },
        {
          name: "Name",
          attributeType: "TEXT",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Users",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Company",
          attributeType: "RELATIONSHIP",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Avatar URL",
          attributeType: "TEXT",
          isSystem: true,
          workspaceId,
        },
        {
          name: "Created at",
          attributeType: "TIMESTAMP",
          isSystem: true,
          workspaceId,
        },
      ],
    },
  },
];
